### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by g-plane** [dprint/dprint-plugin-biome#14]
At this moment, Biome has added support for GraphQL. And, as mentioned in https://github.com/refined-github/refined-github/issues/7372#issuecomment-2253634153 , we should consider adding it to this plugin.

To allow developers to format GraphQL with Biome only, we must add an option called `js_enabled`, which can let developers format JS/TS with other tools while formatting GraphQL with Biome.

**Comment by dsherret** [comment]
@g-plane would you be up for adding it? Also, yeah adding a `js.enabled` option would be good where it's enabled by default.

**Comment by g-plane** [comment]
I can do this.

**Comment by dsherret** [comment]
Thanks!

**Comment by Eveeifyeve** [comment]
I can do this as I know how biome and dprint work.

**Comment by Eveeifyeve** [comment]
I will create a fork and add support for graph ql, partial support for astro, vue & svelte as I want to have the support for formating my frontend for astro for https://teaclient.net.

**Comment by Eveeifyeve** [comment]
Hey Unfortunately biome needs to release a version with the graph ql formater till then I can't support it sadly.

**Comment by Eveeifyeve** [comment]
Feel free @dsherret to close this issue for now as biome hasn't released graph ql formmater in release.

**Comment by Eveeifyeve** [comment]
Hey in a week 1.9 will release which will include graph ql formmater [as said in discord](https://discord.com/channels/1132231889290285117/1132231889911029825/1281600679559041036) after that is out I will update all packages and look into supporting graph ql.

**Comment by Eveeifyeve** [comment]
Hey good news Biome released 1.9 which includes graphql, I will start looking into starting a pr to add support for this.
